// <auto-generated />
using System;
using Hagigabestyle.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hagigabestyle.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Hagigabestyle.API.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Hagigabestyle.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameHe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "http://localhost:5173/images/cat-plates-cups.jpg",
                            IsActive = true,
                            NameEn = "Plates & Cups",
                            NameHe = "צלחות וכוסות",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "http://localhost:5173/images/cat-napkins.jpg",
                            IsActive = true,
                            NameEn = "Napkins & Tablecloths",
                            NameHe = "מפיות ומפות",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "http://localhost:5173/images/cat-balloons.jpg",
                            IsActive = true,
                            NameEn = "Balloons & Decorations",
                            NameHe = "בלונים וקישוטים",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "http://localhost:5173/images/cat-cutlery.jpg",
                            IsActive = true,
                            NameEn = "Disposable Cutlery",
                            NameHe = "סכום חד פעמי",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "http://localhost:5173/images/cat-party.jpg",
                            IsActive = true,
                            NameEn = "Party Accessories",
                            NameHe = "אביזרים למסיבה",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("Hagigabestyle.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranzilaTransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Hagigabestyle.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Hagigabestyle.API.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionHe")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameHe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OriginalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionEn = "Perfect birthday package - includes plates, cups, napkins, cutlery and balloons",
                            DescriptionHe = "מארז מושלם ליום הולדת - כולל צלחות, כוסות, מפיות, סכום ובלונים",
                            ImageUrl = "http://localhost:5173/images/pkg-birthday.jpg",
                            IsActive = true,
                            NameEn = "Classic Birthday Package",
                            NameHe = "מארז יום הולדת קלאסי",
                            OriginalPrice = 189.50m,
                            Price = 149.90m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionEn = "Premium gold package - plates, cups, napkins, tablecloth, cutlery, balloons and decorations",
                            DescriptionHe = "מארז פרימיום בזהב - צלחות, כוסות, מפיות, מפה, סכום, בלונים וקישוטים",
                            ImageUrl = "http://localhost:5173/images/pkg-gold-premium.jpg",
                            IsActive = true,
                            NameEn = "Premium Gold Party Package",
                            NameHe = "מארז מסיבה זהב פרימיום",
                            OriginalPrice = 322.20m,
                            Price = 249.90m
                        });
                });

            modelBuilder.Entity("Hagigabestyle.API.Models.PackageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProductId");

                    b.ToTable("PackageItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PackageId = 1,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            PackageId = 1,
                            ProductId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            PackageId = 1,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            PackageId = 1,
                            ProductId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            PackageId = 1,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            PackageId = 2,
                            ProductId = 1,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 7,
                            PackageId = 2,
                            ProductId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 8,
                            PackageId = 2,
                            ProductId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 9,
                            PackageId = 2,
                            ProductId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 10,
                            PackageId = 2,
                            ProductId = 7,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 11,
                            PackageId = 2,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 12,
                            PackageId = 2,
                            ProductId = 6,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Hagigabestyle.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionHe")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameHe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionEn = "Gold disposable plates, pack of 10",
                            DescriptionHe = "צלחות חד פעמיות בצבע זהב, חבילה של 10",
                            ImageUrl = "http://localhost:5173/images/prod-gold-plates.jpg",
                            IsActive = true,
                            NameEn = "Gold Plates 10 pcs",
                            NameHe = "צלחות זהב 10 יח'",
                            Price = 29.90m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionEn = "Quality transparent cups, pack of 20",
                            DescriptionHe = "כוסות שקופות איכותיות, חבילה של 20",
                            ImageUrl = "http://localhost:5173/images/prod-crystal-cups.jpg",
                            IsActive = true,
                            NameEn = "Crystal Cups 20 pcs",
                            NameHe = "כוסות קריסטל 20 יח'",
                            Price = 24.90m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionEn = "Quality paper napkins, pack of 50",
                            DescriptionHe = "מפיות נייר איכותיות, חבילה של 50",
                            ImageUrl = "http://localhost:5173/images/prod-napkins.jpg",
                            IsActive = true,
                            NameEn = "Premium Napkins 50 pcs",
                            NameHe = "מפיות פרימיום 50 יח'",
                            Price = 19.90m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionEn = "Gold disposable tablecloth",
                            DescriptionHe = "מפת שולחן חד פעמית בצבע זהב",
                            ImageUrl = "http://localhost:5173/images/prod-gold-tablecloth.jpg",
                            IsActive = true,
                            NameEn = "Gold Tablecloth",
                            NameHe = "מפת שולחן זהב",
                            Price = 14.90m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionEn = "Colorful helium balloons",
                            DescriptionHe = "בלונים צבעוניים עם הליום",
                            ImageUrl = "http://localhost:5173/images/prod-balloons.jpg",
                            IsActive = true,
                            NameEn = "Helium Balloons 10 pcs",
                            NameHe = "בלוני הליום 10 יח'",
                            Price = 49.90m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionEn = "Colorful flag garland for decoration",
                            DescriptionHe = "שרשרת דגלונים צבעונית לקישוט",
                            ImageUrl = "http://localhost:5173/images/prod-garland.jpg",
                            IsActive = true,
                            NameEn = "Flag Garland",
                            NameHe = "שרשרת דגלונים",
                            Price = 22.90m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionEn = "Gold knife, fork and spoon set",
                            DescriptionHe = "סכין, מזלג וכפית בצבע זהב",
                            ImageUrl = "http://localhost:5173/images/prod-cutlery-set.jpg",
                            IsActive = true,
                            NameEn = "Gold Cutlery Set 30 pcs",
                            NameHe = "סט סכום זהב 30 יח'",
                            Price = 34.90m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionEn = "Colorful party hats, pack of 6",
                            DescriptionHe = "כובעי מסיבה צבעוניים, חבילה של 6",
                            ImageUrl = "http://localhost:5173/images/prod-party-hats.jpg",
                            IsActive = true,
                            NameEn = "Party Hats 6 pcs",
                            NameHe = "כובעי מסיבה 6 יח'",
                            Price = 15.90m,
                            StockQuantity = 70
                        });
                });

            modelBuilder.Entity("Hagigabestyle.API.Models.OrderItem", b =>
                {
                    b.HasOne("Hagigabestyle.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hagigabestyle.API.Models.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId");

                    b.HasOne("Hagigabestyle.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Package");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Hagigabestyle.API.Models.PackageItem", b =>
                {
                    b.HasOne("Hagigabestyle.API.Models.Package", "Package")
                        .WithMany("PackageItems")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hagigabestyle.API.Models.Product", "Product")
                        .WithMany("PackageItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Hagigabestyle.API.Models.Product", b =>
                {
                    b.HasOne("Hagigabestyle.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Hagigabestyle.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Hagigabestyle.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Hagigabestyle.API.Models.Package", b =>
                {
                    b.Navigation("PackageItems");
                });

            modelBuilder.Entity("Hagigabestyle.API.Models.Product", b =>
                {
                    b.Navigation("PackageItems");
                });
#pragma warning restore 612, 618
        }
    }
}
